-- Autorizaciones docentes para prestamos de equipo.
-- La cedula identifica a la persona, pero toda escritura exige una sesion autenticada.

alter table public.profiles
  add column if not exists national_id text;

create unique index if not exists profiles_national_id_unique
  on public.profiles (national_id)
  where national_id is not null;

alter table public.teacher_registry
  add column if not exists national_id text;

create unique index if not exists teacher_registry_national_id_unique
  on public.teacher_registry (national_id)
  where national_id is not null;

create table if not exists public.academic_students (
  id bigint generated by default as identity primary key,
  national_id text not null unique,
  full_name text not null check (char_length(trim(full_name)) between 3 and 140),
  email text,
  career text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_enrollments (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.reservation_cycles(id) on delete cascade,
  student_id bigint not null references public.academic_students(id) on delete cascade,
  course_code text not null,
  course_name text not null,
  nrc text not null,
  group_code text,
  created_at timestamptz not null default now(),
  unique (cycle_id, student_id, nrc)
);

create table if not exists public.equipment_authorizations (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete restrict,
  cycle_id uuid references public.reservation_cycles(id) on delete set null,
  scope text not null check (scope in ('course', 'individual')),
  course_code text,
  course_name text,
  nrc text,
  group_code text,
  student_id bigint references public.academic_students(id) on delete restrict,
  reason text not null check (reason in ('course_trip', 'supervised_practice', 'other')),
  reason_detail text,
  active boolean not null default true,
  authorized_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint equipment_authorization_target_check check (
    (scope = 'course' and nrc is not null and student_id is null)
    or (scope = 'individual' and student_id is not null and nrc is null)
  ),
  constraint equipment_authorization_reason_detail_check check (
    reason <> 'other' or char_length(trim(coalesce(reason_detail, ''))) between 3 and 240
  )
);

create index if not exists course_enrollments_student_idx
  on public.course_enrollments (student_id, cycle_id);
create index if not exists equipment_authorizations_teacher_idx
  on public.equipment_authorizations (teacher_id, authorized_at desc);
create index if not exists equipment_authorizations_course_idx
  on public.equipment_authorizations (cycle_id, nrc) where active;
create index if not exists equipment_authorizations_student_idx
  on public.equipment_authorizations (student_id) where active;

drop trigger if exists academic_students_set_updated_at on public.academic_students;
create trigger academic_students_set_updated_at
before update on public.academic_students
for each row execute function public.set_updated_at();

alter table public.academic_students enable row level security;
alter table public.course_enrollments enable row level security;
alter table public.equipment_authorizations enable row level security;

revoke all on table public.academic_students, public.course_enrollments, public.equipment_authorizations from anon, authenticated;
grant select on table public.equipment_authorizations to authenticated;

drop policy if exists "Docente consulta sus autorizaciones de equipo" on public.equipment_authorizations;
create policy "Docente consulta sus autorizaciones de equipo"
on public.equipment_authorizations for select to authenticated
using (teacher_id = (select auth.uid()) or public.is_admin());

create or replace function public.my_equipment_courses(p_national_id text)
returns table (
  cycle_id uuid,
  cycle_name text,
  course_code text,
  course_name text,
  nrc text,
  group_code text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  teacher public.profiles;
begin
  select * into teacher
  from public.profiles
  where id = (select auth.uid()) and active = true and role = 'teacher';

  if not found then
    raise exception using errcode = '42501', message = 'Se requiere una cuenta docente activa';
  end if;
  if teacher.national_id is null or regexp_replace(teacher.national_id, '[^0-9]', '', 'g') <> regexp_replace(coalesce(p_national_id, ''), '[^0-9]', '', 'g') then
    raise exception using errcode = '42501', message = 'La cedula no coincide con la cuenta docente';
  end if;

  return query
  select distinct c.id, c.name, f.course_code, f.course_name, f.nrc, f.group_code
  from public.fixed_occupancies f
  join public.reservation_cycles c on c.id = f.cycle_id and c.is_current = true
  where f.nrc is not null
    and regexp_replace(upper(coalesce(f.professor_name, '')), '[^A-Z0-9]', '', 'g')
      like '%' || regexp_replace(upper(teacher.full_name), '[^A-Z0-9]', '', 'g') || '%'
  order by f.course_name, f.nrc;
end;
$$;

create or replace function public.find_equipment_student(p_national_id text)
returns table (student_id bigint, national_id text, full_name text, email text, career text)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.profiles where id = (select auth.uid()) and active = true and role = 'teacher') then
    raise exception using errcode = '42501', message = 'Se requiere una cuenta docente activa';
  end if;
  return query
  select s.id, s.national_id, s.full_name, s.email, s.career
  from public.academic_students s
  where s.active = true
    and regexp_replace(s.national_id, '[^0-9]', '', 'g') = regexp_replace(coalesce(p_national_id, ''), '[^0-9]', '', 'g')
  limit 1;
end;
$$;

create or replace function public.authorize_equipment_course(
  p_cycle_id uuid, p_nrc text, p_reason text, p_reason_detail text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  teacher public.profiles;
  selected_course record;
  saved_id uuid;
begin
  select * into teacher from public.profiles where id = (select auth.uid()) and active = true and role = 'teacher';
  if not found then raise exception using errcode = '42501', message = 'Se requiere una cuenta docente activa'; end if;
  if p_reason not in ('course_trip', 'supervised_practice', 'other') then raise exception using errcode = '22023', message = 'Motivo no valido'; end if;
  if p_reason = 'other' and char_length(trim(coalesce(p_reason_detail, ''))) < 3 then raise exception using errcode = '22023', message = 'Especifique el motivo'; end if;

  select f.course_code, f.course_name, f.nrc, f.group_code into selected_course
  from public.fixed_occupancies f
  where f.cycle_id = p_cycle_id and f.nrc = trim(p_nrc)
    and regexp_replace(upper(coalesce(f.professor_name, '')), '[^A-Z0-9]', '', 'g')
      like '%' || regexp_replace(upper(teacher.full_name), '[^A-Z0-9]', '', 'g') || '%'
  limit 1;
  if not found then raise exception using errcode = '42501', message = 'El curso no pertenece al docente'; end if;

  update public.equipment_authorizations set active = false, revoked_at = now()
  where teacher_id = teacher.id and cycle_id = p_cycle_id and scope = 'course' and nrc = selected_course.nrc and active;
  insert into public.equipment_authorizations
    (teacher_id, cycle_id, scope, course_code, course_name, nrc, group_code, reason, reason_detail)
  values
    (teacher.id, p_cycle_id, 'course', selected_course.course_code, selected_course.course_name, selected_course.nrc,
     selected_course.group_code, p_reason, nullif(trim(coalesce(p_reason_detail, '')), ''))
  returning id into saved_id;
  return saved_id;
end;
$$;

create or replace function public.authorize_equipment_student(
  p_student_id bigint, p_reason text, p_reason_detail text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  teacher public.profiles;
  saved_id uuid;
begin
  select * into teacher from public.profiles where id = (select auth.uid()) and active = true and role = 'teacher';
  if not found then raise exception using errcode = '42501', message = 'Se requiere una cuenta docente activa'; end if;
  if not exists (select 1 from public.academic_students where id = p_student_id and active = true) then raise exception using errcode = '22023', message = 'Estudiante no encontrado'; end if;
  if p_reason not in ('course_trip', 'supervised_practice', 'other') then raise exception using errcode = '22023', message = 'Motivo no valido'; end if;
  if p_reason = 'other' and char_length(trim(coalesce(p_reason_detail, ''))) < 3 then raise exception using errcode = '22023', message = 'Especifique el motivo'; end if;

  insert into public.equipment_authorizations (teacher_id, scope, student_id, reason, reason_detail)
  values (teacher.id, 'individual', p_student_id, p_reason, nullif(trim(coalesce(p_reason_detail, '')), ''))
  returning id into saved_id;
  return saved_id;
end;
$$;

revoke all on function public.my_equipment_courses(text) from public, anon;
revoke all on function public.find_equipment_student(text) from public, anon;
revoke all on function public.authorize_equipment_course(uuid, text, text, text) from public, anon;
revoke all on function public.authorize_equipment_student(bigint, text, text) from public, anon;
grant execute on function public.my_equipment_courses(text) to authenticated;
grant execute on function public.find_equipment_student(text) to authenticated;
grant execute on function public.authorize_equipment_course(uuid, text, text, text) to authenticated;
grant execute on function public.authorize_equipment_student(bigint, text, text) to authenticated;

comment on table public.equipment_authorizations is 'Vistos buenos docentes para prestamos de equipo, por curso completo o estudiante individual';
