create table public.equipment_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique,
  available_quantity integer not null default 0 check (available_quantity >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.student_loan_requests (
  id bigint generated by default as identity primary key,
  request_number text unique,
  student_id bigint not null references public.academic_students(id) on delete restrict,
  authorization_id uuid not null references public.equipment_authorizations(id) on delete restrict,
  expected_return_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending','approved','delivered','returned','cancelled','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expected_return_at > created_at)
);

create table public.student_loan_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.student_loan_requests(id) on delete cascade,
  equipment_catalog_id bigint not null references public.equipment_catalog(id) on delete restrict,
  quantity integer not null check (quantity between 1 and 20),
  unique (request_id, equipment_catalog_id)
);

create index student_loan_requests_student_idx on public.student_loan_requests(student_id, created_at desc);
create index student_loan_requests_status_idx on public.student_loan_requests(status, created_at);

create trigger equipment_catalog_set_updated_at before update on public.equipment_catalog
for each row execute function public.set_updated_at();
create trigger student_loan_requests_set_updated_at before update on public.student_loan_requests
for each row execute function public.set_updated_at();

create or replace function public.set_student_request_number()
returns trigger language plpgsql set search_path = public as $$
begin
  new.request_number := lpad(new.id::text, 4, '0') || '-' || extract(year from new.created_at)::integer;
  return new;
end; $$;
create trigger student_request_number before insert on public.student_loan_requests
for each row execute function public.set_student_request_number();

alter table public.equipment_catalog enable row level security;
alter table public.student_loan_requests enable row level security;
alter table public.student_loan_request_items enable row level security;
revoke all on public.equipment_catalog, public.student_loan_requests, public.student_loan_request_items from anon, authenticated;

create or replace function public.student_loan_context(p_national_id text)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare s public.academic_students; auth_record public.equipment_authorizations; result jsonb;
begin
  if char_length(regexp_replace(coalesce(p_national_id,''),'[^0-9]','','g')) not between 7 and 20 then
    raise exception using errcode='22023', message='Cedula invalida';
  end if;
  select * into s from public.academic_students
  where active and regexp_replace(national_id,'[^0-9]','','g')=regexp_replace(p_national_id,'[^0-9]','','g') limit 1;
  if not found then return jsonb_build_object('found',false); end if;

  select a.* into auth_record from public.equipment_authorizations a
  where a.active and a.scope='individual' and a.student_id=s.id
  order by a.authorized_at desc limit 1;
  if not found then
    select a.* into auth_record from public.equipment_authorizations a
    join public.course_enrollments e on e.student_id=s.id and e.cycle_id=a.cycle_id and e.nrc=a.nrc
    where a.active and a.scope='course'
    order by a.authorized_at desc limit 1;
  end if;

  result := jsonb_build_object(
    'found',true,'student_id',s.id,'full_name',s.full_name,'career',s.career,
    'authorized',auth_record.id is not null,
    'authorization_id',auth_record.id,
    'authorization_label',case when auth_record.scope='course' then coalesce(auth_record.course_code,'Curso')||' · NRC '||auth_record.nrc else 'Autorizacion individual' end,
    'equipment',(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'available',c.available_quantity) order by c.sort_order,c.name),'[]'::jsonb) from public.equipment_catalog c where c.active and c.available_quantity>0)
  );
  return result;
end; $$;

create or replace function public.create_student_loan_request(
  p_national_id text, p_authorization_id uuid, p_expected_return_at timestamptz, p_items jsonb
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare s public.academic_students; auth_record public.equipment_authorizations; request_id bigint; request_code text; item jsonb; catalog public.equipment_catalog;
begin
  if p_expected_return_at <= now() or p_expected_return_at > now()+interval '90 days' then
    raise exception using errcode='22023', message='Fecha de devolucion invalida';
  end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items) not between 1 and 30 then
    raise exception using errcode='22023', message='Seleccione al menos un equipo';
  end if;
  select * into s from public.academic_students where active and regexp_replace(national_id,'[^0-9]','','g')=regexp_replace(coalesce(p_national_id,''),'[^0-9]','','g') limit 1;
  if not found then raise exception using errcode='22023', message='Estudiante no encontrado'; end if;
  select * into auth_record from public.equipment_authorizations where id=p_authorization_id and active;
  if not found or not (
    (auth_record.scope='individual' and auth_record.student_id=s.id) or
    (auth_record.scope='course' and exists(select 1 from public.course_enrollments e where e.student_id=s.id and e.cycle_id=auth_record.cycle_id and e.nrc=auth_record.nrc))
  ) then raise exception using errcode='42501', message='No existe autorizacion docente vigente'; end if;

  insert into public.student_loan_requests(student_id,authorization_id,expected_return_at)
  values(s.id,auth_record.id,p_expected_return_at) returning id,request_number into request_id,request_code;
  for item in select * from jsonb_array_elements(p_items) loop
    select * into catalog from public.equipment_catalog where id=(item->>'id')::bigint and active for update;
    if not found or (item->>'quantity')::integer not between 1 and least(20,catalog.available_quantity) then
      raise exception 'Cantidad no disponible para %', coalesce(catalog.name,'equipo') using errcode='22023';
    end if;
    insert into public.student_loan_request_items(request_id,equipment_catalog_id,quantity)
    values(request_id,catalog.id,(item->>'quantity')::integer);
  end loop;
  return jsonb_build_object('ok',true,'request_number',request_code,'request_id',request_id);
end; $$;

revoke all on function public.student_loan_context(text) from public, authenticated;
revoke all on function public.create_student_loan_request(text,uuid,timestamptz,jsonb) from public, authenticated;
grant execute on function public.student_loan_context(text) to anon;
grant execute on function public.create_student_loan_request(text,uuid,timestamptz,jsonb) to anon;

insert into public.equipment_catalog(name,available_quantity,sort_order) values
('GPS de mano',5,1),('Cinta métrica',12,2),('Cinta diamétrica',8,3),('Clinómetro',4,4),('Brújula',6,5)
on conflict(name) do update set available_quantity=excluded.available_quantity,active=true,sort_order=excluded.sort_order;
