-- Administración de profesores autorizadores y asignaciones explícitas por ciclo.

alter table public.teacher_registry alter column email drop not null;

create table if not exists public.equipment_teacher_courses (
  id bigint generated by default as identity primary key,
  teacher_registry_id bigint not null references public.teacher_registry(id) on delete cascade,
  cycle_id uuid not null references public.reservation_cycles(id) on delete cascade,
  course_code text not null,
  course_name text not null,
  nrc text not null,
  group_code text,
  created_at timestamptz not null default now(),
  unique (teacher_registry_id, cycle_id, nrc)
);

alter table public.equipment_authorizations
  add column if not exists teacher_registry_id bigint references public.teacher_registry(id) on delete restrict;
alter table public.equipment_authorizations alter column teacher_id drop not null;

update public.equipment_authorizations a
set teacher_registry_id = tr.id
from public.profiles p
join public.teacher_registry tr on lower(tr.email) = lower(p.email)
where a.teacher_id = p.id and a.teacher_registry_id is null;

alter table public.equipment_teacher_courses enable row level security;
revoke all on table public.equipment_teacher_courses from anon, authenticated;

create or replace function public.warehouse_professors_data()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare result jsonb;
begin
  if not public.is_warehouse_staff() then raise exception using errcode='42501', message='Acceso exclusivo para personal de bodega'; end if;
  select jsonb_build_object(
    'professors', (select coalesce(jsonb_agg(jsonb_build_object(
      'id',tr.id,'full_name',tr.full_name,'national_id',tr.national_id,'email',tr.email,'active',tr.active,
      'courses',(select coalesce(jsonb_agg(to_jsonb(tc) order by tc.cycle_name,tc.course_name,tc.nrc),'[]'::jsonb) from (
        select x.id,x.cycle_id,c.name cycle_name,x.course_code,x.course_name,x.nrc,x.group_code
        from public.equipment_teacher_courses x join public.reservation_cycles c on c.id=x.cycle_id
        where x.teacher_registry_id=tr.id) tc),
      'authorizations',(select coalesce(jsonb_agg(jsonb_build_object(
        'id',a.id,'scope',a.scope,'course_name',a.course_name,'course_code',a.course_code,'nrc',a.nrc,
        'student_name',s.full_name,'student_national_id',s.national_id,'reason',a.reason,'reason_detail',a.reason_detail,
        'active',a.active,'authorized_at',a.authorized_at) order by a.authorized_at desc),'[]'::jsonb)
        from public.equipment_authorizations a left join public.academic_students s on s.id=a.student_id
        left join public.profiles p on p.id=a.teacher_id
        where a.teacher_registry_id=tr.id or (a.teacher_registry_id is null and lower(p.email)=lower(tr.email)))
    ) order by tr.full_name),'[]'::jsonb) from public.teacher_registry tr),
    'courses',(select coalesce(jsonb_agg(to_jsonb(q) order by q.cycle_name,q.course_name,q.nrc),'[]'::jsonb) from (
      select distinct f.cycle_id,c.name cycle_name,f.course_code,f.course_name,f.nrc,f.group_code
      from public.fixed_occupancies f join public.reservation_cycles c on c.id=f.cycle_id
      where f.nrc is not null
    ) q)
  ) into result;
  return result;
end $$;

create or replace function public.warehouse_save_professor(p_id bigint,p_full_name text,p_national_id text,p_email text default null,p_active boolean default true)
returns bigint language plpgsql security definer set search_path='' as $$
declare saved_id bigint; clean_id text:=regexp_replace(coalesce(p_national_id,''),'[^0-9]','','g');
begin
  if not public.is_warehouse_staff() then raise exception using errcode='42501', message='Acceso exclusivo para personal de bodega'; end if;
  if char_length(trim(coalesce(p_full_name,'')))<3 then raise exception using errcode='22023',message='Ingrese el nombre completo'; end if;
  if char_length(clean_id) not between 7 and 20 then raise exception using errcode='22023',message='Revise la cédula'; end if;
  if nullif(trim(coalesce(p_email,'')),'') is not null and lower(trim(p_email)) !~ '^[a-z0-9-]+\.[a-z0-9-]+\.[a-z0-9-]+@una\.cr$' then
    raise exception using errcode='22023',message='El correo institucional no tiene el formato esperado';
  end if;
  if p_id is null then
    insert into public.teacher_registry(full_name,national_id,email,active)
    values(trim(p_full_name),clean_id,nullif(lower(trim(coalesce(p_email,''))),''),coalesce(p_active,true)) returning id into saved_id;
  else
    update public.teacher_registry set full_name=trim(p_full_name),national_id=clean_id,email=nullif(lower(trim(coalesce(p_email,''))),''),active=coalesce(p_active,true)
    where id=p_id returning id into saved_id;
    if saved_id is null then raise exception using errcode='P0002',message='Profesor no encontrado'; end if;
  end if;
  update public.profiles p set full_name=trim(p_full_name),national_id=clean_id,active=coalesce(p_active,true)
  where nullif(lower(trim(coalesce(p_email,''))),'') is not null and lower(p.email)=lower(trim(p_email)) and p.role='teacher';
  return saved_id;
end $$;

create or replace function public.warehouse_assign_professor_course(p_teacher_id bigint,p_cycle_id uuid,p_nrc text)
returns bigint language plpgsql security definer set search_path='' as $$
declare course record; saved_id bigint;
begin
  if not public.is_warehouse_staff() then raise exception using errcode='42501', message='Acceso exclusivo para personal de bodega'; end if;
  select f.course_code,f.course_name,f.nrc,f.group_code into course from public.fixed_occupancies f
  where f.cycle_id=p_cycle_id and f.nrc=trim(p_nrc) limit 1;
  if not found then raise exception using errcode='P0002',message='Curso no encontrado'; end if;
  insert into public.equipment_teacher_courses(teacher_registry_id,cycle_id,course_code,course_name,nrc,group_code)
  values(p_teacher_id,p_cycle_id,course.course_code,course.course_name,course.nrc,course.group_code)
  on conflict(teacher_registry_id,cycle_id,nrc) do update set course_code=excluded.course_code,course_name=excluded.course_name,group_code=excluded.group_code
  returning id into saved_id; return saved_id;
end $$;

create or replace function public.warehouse_remove_professor_course(p_assignment_id bigint)
returns void language plpgsql security definer set search_path='' as $$
begin
  if not public.is_warehouse_staff() then raise exception using errcode='42501', message='Acceso exclusivo para personal de bodega'; end if;
  delete from public.equipment_teacher_courses where id=p_assignment_id;
end $$;

create or replace function public.public_equipment_teacher_context(p_national_id text)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare teacher public.teacher_registry; result jsonb;
begin
  if char_length(regexp_replace(coalesce(p_national_id,''),'[^0-9]','','g')) not between 7 and 20 then raise exception using errcode='22023',message='Revise el número de cédula'; end if;
  select * into teacher from public.teacher_registry where active and regexp_replace(coalesce(national_id,''),'[^0-9]','','g')=regexp_replace(p_national_id,'[^0-9]','','g') limit 1;
  if not found then return jsonb_build_object('found',false); end if;
  select jsonb_build_object('found',true,'teacher_name',teacher.full_name,'courses',(
    select coalesce(jsonb_agg(to_jsonb(q) order by q.cycle_name,q.course_name,q.nrc),'[]'::jsonb) from (
      select x.cycle_id,c.name cycle_name,x.course_code,x.course_name,x.nrc,x.group_code
      from public.equipment_teacher_courses x join public.reservation_cycles c on c.id=x.cycle_id
      where x.teacher_registry_id=teacher.id) q)) into result;
  return result;
end $$;

create or replace function public.public_authorize_equipment_course(p_teacher_national_id text,p_cycle_id uuid,p_nrc text,p_reason text,p_reason_detail text default null,p_signature_data text default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare teacher public.teacher_registry; profile_id uuid; selected_course record; saved_id uuid;
begin
  select * into teacher from public.teacher_registry where active and regexp_replace(coalesce(national_id,''),'[^0-9]','','g')=regexp_replace(coalesce(p_teacher_national_id,''),'[^0-9]','','g') limit 1;
  if not found then raise exception using errcode='42501',message='Profesor no registrado'; end if;
  if p_reason not in ('course_trip','supervised_practice','other') or (p_reason='other' and char_length(trim(coalesce(p_reason_detail,'')))<3) then raise exception using errcode='22023',message='Indique un motivo válido'; end if;
  if p_signature_data is null or p_signature_data !~ '^data:image/png;base64,' then raise exception using errcode='22023',message='La firma del profesor es obligatoria'; end if;
  select x.course_code,x.course_name,x.nrc,x.group_code into selected_course from public.equipment_teacher_courses x where x.teacher_registry_id=teacher.id and x.cycle_id=p_cycle_id and x.nrc=trim(p_nrc) limit 1;
  if not found then raise exception using errcode='42501',message='El curso no está asignado al profesor'; end if;
  select p.id into profile_id from public.profiles p where teacher.email is not null and lower(p.email)=lower(teacher.email) limit 1;
  update public.equipment_authorizations set active=false,revoked_at=now() where teacher_registry_id=teacher.id and cycle_id=p_cycle_id and scope='course' and nrc=selected_course.nrc and active;
  insert into public.equipment_authorizations(teacher_id,teacher_registry_id,cycle_id,scope,course_code,course_name,nrc,group_code,reason,reason_detail,signature_data)
  values(profile_id,teacher.id,p_cycle_id,'course',selected_course.course_code,selected_course.course_name,selected_course.nrc,selected_course.group_code,p_reason,nullif(trim(coalesce(p_reason_detail,'')),''),p_signature_data) returning id into saved_id;
  return saved_id;
end $$;

create or replace function public.public_authorize_equipment_student(p_teacher_national_id text,p_student_id bigint,p_reason text,p_reason_detail text default null,p_signature_data text default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare teacher public.teacher_registry; profile_id uuid; saved_id uuid;
begin
  select * into teacher from public.teacher_registry where active and regexp_replace(coalesce(national_id,''),'[^0-9]','','g')=regexp_replace(coalesce(p_teacher_national_id,''),'[^0-9]','','g') limit 1;
  if not found then raise exception using errcode='42501',message='Profesor no registrado'; end if;
  if not exists(select 1 from public.academic_students where id=p_student_id and active) then raise exception using errcode='P0002',message='Estudiante no encontrado'; end if;
  if p_reason not in ('course_trip','supervised_practice','other') or (p_reason='other' and char_length(trim(coalesce(p_reason_detail,'')))<3) then raise exception using errcode='22023',message='Indique un motivo válido'; end if;
  if p_signature_data is null or p_signature_data !~ '^data:image/png;base64,' then raise exception using errcode='22023',message='La firma del profesor es obligatoria'; end if;
  select p.id into profile_id from public.profiles p where teacher.email is not null and lower(p.email)=lower(teacher.email) limit 1;
  insert into public.equipment_authorizations(teacher_id,teacher_registry_id,scope,student_id,reason,reason_detail,signature_data)
  values(profile_id,teacher.id,'individual',p_student_id,p_reason,nullif(trim(coalesce(p_reason_detail,'')),''),p_signature_data) returning id into saved_id;
  return saved_id;
end $$;

revoke all on function public.warehouse_professors_data() from public,anon;
revoke all on function public.warehouse_save_professor(bigint,text,text,text,boolean) from public,anon;
revoke all on function public.warehouse_assign_professor_course(bigint,uuid,text) from public,anon;
revoke all on function public.warehouse_remove_professor_course(bigint) from public,anon;
grant execute on function public.warehouse_professors_data() to authenticated;
grant execute on function public.warehouse_save_professor(bigint,text,text,text,boolean) to authenticated;
grant execute on function public.warehouse_assign_professor_course(bigint,uuid,text) to authenticated;
grant execute on function public.warehouse_remove_professor_course(bigint) to authenticated;
grant execute on function public.public_equipment_teacher_context(text) to anon;
grant execute on function public.public_authorize_equipment_course(text,uuid,text,text,text,text) to anon;
grant execute on function public.public_authorize_equipment_student(text,bigint,text,text,text) to anon;
