-- Importación semestral idempotente de estudiantes y matrículas desde Bodega.
create table if not exists public.student_import_batches (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.reservation_cycles(id) on delete restrict,
  source_file text not null,
  source_rows integer not null,
  students_upserted integer not null,
  enrollments_created integer not null,
  unmatched_course_codes text[] not null default '{}',
  imported_by uuid not null references public.profiles(id) on delete restrict,
  imported_at timestamptz not null default now()
);

alter table public.student_import_batches enable row level security;
revoke all on table public.student_import_batches from anon, authenticated;

create or replace function public.warehouse_import_students(
  p_cycle_id uuid,
  p_source_file text,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_count integer;
  student_count integer;
  enrollment_count integer;
  unmatched text[];
  batch_id bigint;
begin
  if not public.is_warehouse_staff() then
    raise exception using errcode='42501', message='Acceso exclusivo para personal de bodega';
  end if;
  if not exists(select 1 from public.reservation_cycles where id=p_cycle_id) then
    raise exception using errcode='22023', message='Seleccione un ciclo válido';
  end if;
  if jsonb_typeof(p_rows)<>'array' then
    raise exception using errcode='22023', message='El archivo no contiene una lista válida';
  end if;
  source_count:=jsonb_array_length(p_rows);
  if source_count<1 or source_count>5000 then
    raise exception using errcode='22023', message='El archivo debe contener entre 1 y 5000 matrículas';
  end if;
  if char_length(trim(coalesce(p_source_file,'')))<5 then
    raise exception using errcode='22023', message='No se pudo identificar el archivo';
  end if;

  if exists(
    select 1 from jsonb_to_recordset(p_rows) as r(national_id text,full_name text,career text,email text,phone text,course_code text,course_name text)
    where char_length(regexp_replace(coalesce(national_id,''),'[^0-9]','','g')) not between 7 and 20
       or char_length(trim(coalesce(full_name,'')))<3
       or trim(coalesce(course_code,''))=''
  ) then
    raise exception using errcode='22023', message='Hay filas con cédula, nombre o código de materia inválidos';
  end if;

  if exists(
    select 1
    from jsonb_to_recordset(p_rows) as r(national_id text,full_name text,career text,email text,phone text)
    group by regexp_replace(national_id,'[^0-9]','','g')
    having count(distinct concat_ws('|',trim(full_name),lower(trim(email)),trim(phone),trim(career)))>1
  ) then
    raise exception using errcode='22023', message='Una misma cédula contiene datos personales diferentes dentro del archivo';
  end if;

  with incoming as (
    select distinct on (regexp_replace(national_id,'[^0-9]','','g'))
      regexp_replace(national_id,'[^0-9]','','g') national_id,
      trim(full_name) full_name,
      nullif(lower(trim(email)),'') email,
      nullif(trim(phone),'') phone,
      case
        when upper(coalesce(career,'')) like '%GESTI%' then 'Ingeniería en Gestión Ambiental'
        when upper(coalesce(career,'')) like '%FOREST%' then 'Ingeniería en Ciencias Forestales'
        else null
      end career
    from jsonb_to_recordset(p_rows) as r(national_id text,full_name text,career text,email text,phone text)
    order by regexp_replace(national_id,'[^0-9]','','g')
  )
  insert into public.academic_students(national_id,full_name,email,phone,career,active)
  select national_id,full_name,email,phone,career,true from incoming
  on conflict(national_id) do update set
    full_name=excluded.full_name,
    email=excluded.email,
    phone=excluded.phone,
    career=excluded.career,
    active=true,
    updated_at=now();

  with incoming_ids as (
    select distinct regexp_replace(national_id,'[^0-9]','','g') national_id
    from jsonb_to_recordset(p_rows) as r(national_id text)
  )
  delete from public.course_enrollments e
  using public.academic_students s, incoming_ids i
  where e.cycle_id=p_cycle_id and e.student_id=s.id and s.national_id=i.national_id;

  with incoming as (
    select regexp_replace(national_id,'[^0-9]','','g') national_id,upper(trim(course_code)) course_code
    from jsonb_to_recordset(p_rows) as r(national_id text,course_code text)
  ), courses as (
    select distinct f.cycle_id,f.course_code,f.course_name,f.nrc,f.group_code
    from public.fixed_occupancies f
    where f.cycle_id=p_cycle_id and f.nrc is not null
  )
  insert into public.course_enrollments(cycle_id,student_id,course_code,course_name,nrc,group_code)
  select distinct c.cycle_id,s.id,c.course_code,c.course_name,c.nrc,c.group_code
  from incoming i
  join public.academic_students s on s.national_id=i.national_id
  join courses c on upper(trim(c.course_code))=i.course_code
  on conflict(cycle_id,student_id,nrc) do update set
    course_code=excluded.course_code,
    course_name=excluded.course_name,
    group_code=excluded.group_code;

  select count(distinct regexp_replace(national_id,'[^0-9]','','g')) into student_count
  from jsonb_to_recordset(p_rows) as r(national_id text);

  select count(*) into enrollment_count
  from public.course_enrollments e
  join public.academic_students s on s.id=e.student_id
  where e.cycle_id=p_cycle_id
    and s.national_id in (
      select distinct regexp_replace(national_id,'[^0-9]','','g')
      from jsonb_to_recordset(p_rows) as r(national_id text)
    );

  select coalesce(array_agg(course_code order by course_code),'{}') into unmatched
  from (
    select distinct upper(trim(r.course_code)) course_code
    from jsonb_to_recordset(p_rows) as r(course_code text)
    where not exists(
      select 1 from public.fixed_occupancies f
      where f.cycle_id=p_cycle_id and f.nrc is not null and upper(trim(f.course_code))=upper(trim(r.course_code))
    )
  ) missing;

  insert into public.student_import_batches(cycle_id,source_file,source_rows,students_upserted,enrollments_created,unmatched_course_codes,imported_by)
  values(p_cycle_id,left(trim(p_source_file),255),source_count,student_count,enrollment_count,unmatched,(select auth.uid()))
  returning id into batch_id;

  return jsonb_build_object(
    'batch_id',batch_id,
    'source_rows',source_count,
    'students',student_count,
    'enrollments',enrollment_count,
    'unmatched_course_codes',to_jsonb(unmatched),
    'history_preserved',true
  );
end;
$$;

revoke all on function public.warehouse_import_students(uuid,text,jsonb) from public,anon;
grant execute on function public.warehouse_import_students(uuid,text,jsonb) to authenticated;

comment on table public.student_import_batches is 'Auditoría sin datos personales de las importaciones semestrales de estudiantes';
comment on function public.warehouse_import_students(uuid,text,jsonb) is 'Actualiza estudiantes por cédula y reemplaza solo matrículas del ciclo elegido; no elimina estudiantes ni préstamos históricos';
