create table public.equipment_units (
  id bigint generated by default as identity primary key,
  catalog_id bigint not null references public.equipment_catalog(id) on delete restrict,
  consecutive_code text not null unique,
  asset_number text unique,
  brand text,
  model text,
  serial_number text unique,
  equipment_use text,
  observations text,
  status text not null default 'available' check (status in ('available','loaned','maintenance','retired')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.loan_request_unit_assignments (
  id bigint generated by default as identity primary key,
  request_item_id bigint not null references public.student_loan_request_items(id) on delete cascade,
  equipment_unit_id bigint not null references public.equipment_units(id) on delete restrict,
  delivered_at timestamptz not null default now(),
  returned_at timestamptz,
  return_note text,
  returned_by text,
  unique (request_item_id, equipment_unit_id)
);

create table public.loan_year_counters (
  year integer primary key,
  last_number integer not null check (last_number > 0)
);

alter table public.student_loan_requests
  add column if not exists student_signature_data text,
  add column if not exists receipt_token uuid not null default gen_random_uuid();
create unique index if not exists student_loan_requests_receipt_token_idx on public.student_loan_requests(receipt_token);
alter table public.student_loan_requests drop constraint if exists student_loan_requests_student_signature_check;
alter table public.student_loan_requests add constraint student_loan_requests_student_signature_check
  check (student_signature_data is null or (student_signature_data like 'data:image/png;base64,%' and char_length(student_signature_data) between 100 and 300000));

create trigger equipment_units_set_updated_at before update on public.equipment_units
for each row execute function public.set_updated_at();
alter table public.equipment_units enable row level security;
alter table public.loan_request_unit_assignments enable row level security;
alter table public.loan_year_counters enable row level security;
revoke all on public.equipment_units, public.loan_request_unit_assignments, public.loan_year_counters from anon, authenticated;

do $$
declare category record; counter integer; code_number integer := 0;
begin
  for category in select id, available_quantity from public.equipment_catalog order by sort_order, id loop
    for counter in 1..category.available_quantity loop
      code_number := code_number + 1;
      insert into public.equipment_units(catalog_id, consecutive_code)
      values(category.id, 'EQ-' || lpad(code_number::text, 4, '0')) on conflict do nothing;
    end loop;
  end loop;
end $$;

create or replace function public.sync_equipment_available_quantity()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  update public.equipment_catalog c set available_quantity=(
    select count(*) from public.equipment_units u where u.catalog_id=c.id and u.active and u.status='available'
  ) where c.id=coalesce(new.catalog_id,old.catalog_id);
  return coalesce(new,old);
end $$;
create trigger equipment_units_sync_quantity after insert or update or delete on public.equipment_units
for each row execute function public.sync_equipment_available_quantity();
update public.equipment_catalog c set available_quantity=(select count(*) from public.equipment_units u where u.catalog_id=c.id and u.active and u.status='available');

create or replace function public.set_student_request_number()
returns trigger language plpgsql security definer set search_path='' as $$
declare request_year integer; next_number integer;
begin
  request_year := extract(year from coalesce(new.created_at,now()))::integer;
  insert into public.loan_year_counters(year,last_number) values(request_year,1)
  on conflict(year) do update set last_number=public.loan_year_counters.last_number+1
  returning last_number into next_number;
  new.request_number := request_year::text || '-' || lpad(next_number::text,3,'0');
  return new;
end $$;

with numbered as (
  select id, extract(year from created_at)::integer as yr, row_number() over(partition by extract(year from created_at) order by created_at,id) as rn
  from public.student_loan_requests
)
update public.student_loan_requests r set request_number=n.yr::text||'-'||lpad(n.rn::text,3,'0') from numbered n where n.id=r.id;
insert into public.loan_year_counters(year,last_number)
select extract(year from created_at)::integer,count(*) from public.student_loan_requests group by 1
on conflict(year) do update set last_number=excluded.last_number;

create or replace function public.create_student_loan_request(
  p_national_id text, p_authorization_id uuid, p_expected_return_at timestamptz, p_items jsonb, p_signature_data text
) returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.academic_students; auth_record public.equipment_authorizations; request_id bigint; request_code text; request_token uuid; item jsonb; catalog public.equipment_catalog;
begin
  if p_expected_return_at<=now() or p_expected_return_at>now()+interval '90 days' then raise exception using errcode='22023',message='Fecha de devolución inválida'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items) not between 1 and 30 then raise exception using errcode='22023',message='Seleccione al menos un equipo'; end if;
  if p_signature_data is null or p_signature_data not like 'data:image/png;base64,%' or char_length(p_signature_data) not between 100 and 300000 then raise exception using errcode='22023',message='La firma del estudiante es obligatoria'; end if;
  select * into s from public.academic_students where active and regexp_replace(national_id,'[^0-9]','','g')=regexp_replace(coalesce(p_national_id,''),'[^0-9]','','g') limit 1;
  if not found then raise exception using errcode='22023',message='Estudiante no encontrado'; end if;
  select * into auth_record from public.equipment_authorizations where id=p_authorization_id and active;
  if not found or not ((auth_record.scope='individual' and auth_record.student_id=s.id) or (auth_record.scope='course' and exists(select 1 from public.course_enrollments e where e.student_id=s.id and e.cycle_id=auth_record.cycle_id and e.nrc=auth_record.nrc))) then raise exception using errcode='42501',message='No existe autorización docente vigente'; end if;
  insert into public.student_loan_requests(student_id,authorization_id,expected_return_at,student_signature_data)
  values(s.id,auth_record.id,p_expected_return_at,p_signature_data) returning id,request_number,receipt_token into request_id,request_code,request_token;
  for item in select * from jsonb_array_elements(p_items) loop
    select * into catalog from public.equipment_catalog where id=(item->>'id')::bigint and active for update;
    if not found or (item->>'quantity')::integer not between 1 and least(20,catalog.available_quantity) then raise exception 'Cantidad no disponible para %',coalesce(catalog.name,'equipo') using errcode='22023'; end if;
    insert into public.student_loan_request_items(request_id,equipment_catalog_id,quantity) values(request_id,catalog.id,(item->>'quantity')::integer);
  end loop;
  return jsonb_build_object('ok',true,'request_number',request_code,'request_id',request_id,'receipt_token',request_token);
end $$;
revoke all on function public.create_student_loan_request(text,uuid,timestamptz,jsonb) from anon;
revoke all on function public.create_student_loan_request(text,uuid,timestamptz,jsonb,text) from public,authenticated;
grant execute on function public.create_student_loan_request(text,uuid,timestamptz,jsonb,text) to anon;

create or replace function public.warehouse_dashboard_data()
returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
  if not public.is_warehouse_staff() then raise exception using errcode='42501',message='Acceso exclusivo para personal de bodega'; end if;
  return jsonb_build_object(
    'staff_name',(select full_name from public.warehouse_staff where user_id=(select auth.uid())),
    'metrics',jsonb_build_object('pending',(select count(*) from public.student_loan_requests where status='pending'),'approved',(select count(*) from public.student_loan_requests where status='approved'),'delivered',(select count(*) from public.student_loan_requests where status='delivered'),'overdue',(select count(*) from public.student_loan_requests where status='delivered' and expected_return_at<now())),
    'requests',(select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'request_number',r.request_number,'status',r.status,'created_at',r.created_at,'expected_return_at',r.expected_return_at,'student_name',s.full_name,'national_id',s.national_id,'email',s.email,'career',s.career,'has_signature',r.student_signature_data is not null,'items',(select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'catalog_id',c.id,'name',c.name,'quantity',i.quantity) order by c.name),'[]'::jsonb) from public.student_loan_request_items i join public.equipment_catalog c on c.id=i.equipment_catalog_id where i.request_id=r.id)) order by case r.status when 'pending' then 1 when 'approved' then 2 when 'delivered' then 3 else 4 end,r.created_at desc),'[]'::jsonb) from public.student_loan_requests r join public.academic_students s on s.id=r.student_id),
    'equipment',(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'available',(select count(*) from public.equipment_units u where u.catalog_id=c.id and u.active and u.status='available'),'total',(select count(*) from public.equipment_units u where u.catalog_id=c.id and u.active),'active',c.active,'units',(select coalesce(jsonb_agg(jsonb_build_object('id',u.id,'code',u.consecutive_code,'asset',u.asset_number,'brand',u.brand,'model',u.model,'serial',u.serial_number,'use',u.equipment_use,'observations',u.observations,'status',u.status,'active',u.active) order by u.consecutive_code),'[]'::jsonb) from public.equipment_units u where u.catalog_id=c.id)) order by c.sort_order,c.name),'[]'::jsonb) from public.equipment_catalog c),
    'clients',(select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'national_id',s.national_id,'full_name',s.full_name,'email',s.email,'career',s.career,'active',s.active,'active_loans',(select count(*) from public.student_loan_requests r where r.student_id=s.id and r.status='delivered')) order by s.full_name),'[]'::jsonb) from public.academic_students s),
    'active_loans',(select coalesce(jsonb_agg(jsonb_build_object('assignment_id',a.id,'request_id',r.id,'request_number',r.request_number,'student_name',s.full_name,'national_id',s.national_id,'email',s.email,'expected_return_at',r.expected_return_at,'item_name',c.name,'unit_id',u.id,'code',u.consecutive_code,'asset',u.asset_number,'brand',u.brand,'model',u.model,'serial',u.serial_number,'delivered_at',a.delivered_at) order by r.request_number,u.consecutive_code),'[]'::jsonb) from public.loan_request_unit_assignments a join public.student_loan_request_items i on i.id=a.request_item_id join public.student_loan_requests r on r.id=i.request_id join public.academic_students s on s.id=r.student_id join public.equipment_catalog c on c.id=i.equipment_catalog_id join public.equipment_units u on u.id=a.equipment_unit_id where a.returned_at is null)
  );
end $$;

create or replace function public.warehouse_save_equipment_unit(p_id bigint,p_catalog_id bigint,p_code text,p_asset text,p_brand text,p_model text,p_serial text,p_use text,p_observations text,p_status text,p_active boolean)
returns bigint language plpgsql security definer set search_path='' as $$
declare saved bigint;
begin
 if not public.is_warehouse_staff() then raise exception using errcode='42501',message='Acceso exclusivo para personal de bodega'; end if;
 if char_length(trim(coalesce(p_code,'')))<2 or p_status not in ('available','loaned','maintenance','retired') then raise exception using errcode='22023',message='Datos del equipo no válidos'; end if;
 if p_id is null then insert into public.equipment_units(catalog_id,consecutive_code,asset_number,brand,model,serial_number,equipment_use,observations,status,active) values(p_catalog_id,trim(p_code),nullif(trim(coalesce(p_asset,'')),''),nullif(trim(coalesce(p_brand,'')),''),nullif(trim(coalesce(p_model,'')),''),nullif(trim(coalesce(p_serial,'')),''),nullif(trim(coalesce(p_use,'')),''),nullif(trim(coalesce(p_observations,'')),''),p_status,coalesce(p_active,true)) returning id into saved;
 else update public.equipment_units set catalog_id=p_catalog_id,consecutive_code=trim(p_code),asset_number=nullif(trim(coalesce(p_asset,'')),''),brand=nullif(trim(coalesce(p_brand,'')),''),model=nullif(trim(coalesce(p_model,'')),''),serial_number=nullif(trim(coalesce(p_serial,'')),''),equipment_use=nullif(trim(coalesce(p_use,'')),''),observations=nullif(trim(coalesce(p_observations,'')),''),status=p_status,active=coalesce(p_active,true) where id=p_id returning id into saved; end if;
 return saved;
end $$;

create or replace function public.warehouse_save_client(p_id bigint,p_national_id text,p_full_name text,p_email text,p_career text,p_active boolean)
returns bigint language plpgsql security definer set search_path='' as $$
declare saved bigint;
begin
 if not public.is_warehouse_staff() then raise exception using errcode='42501',message='Acceso exclusivo para personal de bodega'; end if;
 if char_length(regexp_replace(coalesce(p_national_id,''),'[^0-9]','','g')) not between 7 and 20 or char_length(trim(coalesce(p_full_name,'')))<3 then raise exception using errcode='22023',message='Datos del estudiante no válidos'; end if;
 if p_id is null then insert into public.academic_students(national_id,full_name,email,career,active) values(regexp_replace(p_national_id,'[^0-9]','','g'),trim(p_full_name),nullif(lower(trim(coalesce(p_email,''))),''),nullif(trim(coalesce(p_career,'')),''),coalesce(p_active,true)) returning id into saved;
 else update public.academic_students set national_id=regexp_replace(p_national_id,'[^0-9]','','g'),full_name=trim(p_full_name),email=nullif(lower(trim(coalesce(p_email,''))),''),career=nullif(trim(coalesce(p_career,'')),''),active=coalesce(p_active,true) where id=p_id returning id into saved; end if;
 return saved;
end $$;

create or replace function public.warehouse_deliver_request(p_request_id bigint,p_unit_ids jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare req public.student_loan_requests; item record; unit_id bigint;
begin
 if not public.is_warehouse_staff() then raise exception using errcode='42501',message='Acceso exclusivo para personal de bodega'; end if;
 select * into req from public.student_loan_requests where id=p_request_id for update;
 if not found or req.status<>'approved' then raise exception using errcode='22023',message='La solicitud no está aprobada'; end if;
 if jsonb_typeof(p_unit_ids)<>'array' then raise exception using errcode='22023',message='Seleccione los equipos por entregar'; end if;
 for item in select i.id,i.equipment_catalog_id,i.quantity from public.student_loan_request_items i where i.request_id=p_request_id loop
   if (select count(*) from jsonb_array_elements_text(p_unit_ids) x join public.equipment_units u on u.id=x::bigint where u.catalog_id=item.equipment_catalog_id)<>item.quantity then raise exception using errcode='22023',message='Seleccione la cantidad exacta de cada tipo de equipo'; end if;
 end loop;
 for unit_id in select value::bigint from jsonb_array_elements_text(p_unit_ids) loop
   if not exists(select 1 from public.equipment_units where id=unit_id and active and status='available' for update) then raise exception using errcode='22023',message='Uno de los equipos ya no está disponible'; end if;
   insert into public.loan_request_unit_assignments(request_item_id,equipment_unit_id) select i.id,unit_id from public.student_loan_request_items i join public.equipment_units u on u.catalog_id=i.equipment_catalog_id where i.request_id=p_request_id and u.id=unit_id;
   update public.equipment_units set status='loaned' where id=unit_id;
 end loop;
 update public.student_loan_requests set status='delivered',processed_by=(select auth.uid()),delivered_at=now() where id=p_request_id;
 return jsonb_build_object('ok',true,'request_id',p_request_id,'receipt_token',req.receipt_token);
end $$;

create or replace function public.warehouse_return_units(p_request_id bigint,p_returns jsonb,p_returned_by text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare entry jsonb; assignment_id bigint; unit_id bigint; completed boolean; token uuid;
begin
 if not public.is_warehouse_staff() then raise exception using errcode='42501',message='Acceso exclusivo para personal de bodega'; end if;
 if char_length(trim(coalesce(p_returned_by,'')))<3 then raise exception using errcode='22023',message='Indique quién entrega los equipos'; end if;
 if jsonb_typeof(p_returns)<>'array' or jsonb_array_length(p_returns)<1 then raise exception using errcode='22023',message='Seleccione al menos un equipo devuelto'; end if;
 for entry in select * from jsonb_array_elements(p_returns) loop
   assignment_id:=(entry->>'assignment_id')::bigint;
   select a.equipment_unit_id into unit_id from public.loan_request_unit_assignments a join public.student_loan_request_items i on i.id=a.request_item_id where a.id=assignment_id and i.request_id=p_request_id and a.returned_at is null for update;
   if not found then raise exception using errcode='22023',message='Equipo devuelto no válido'; end if;
   update public.loan_request_unit_assignments set returned_at=now(),returned_by=trim(p_returned_by),return_note=nullif(trim(coalesce(entry->>'note','')),'') where id=assignment_id;
   update public.equipment_units set status='available' where id=unit_id;
 end loop;
 completed:=not exists(select 1 from public.loan_request_unit_assignments a join public.student_loan_request_items i on i.id=a.request_item_id where i.request_id=p_request_id and a.returned_at is null);
 update public.student_loan_requests set status=case when completed then 'returned' else 'delivered' end,returned_at=case when completed then now() else returned_at end,processed_by=(select auth.uid()) where id=p_request_id returning receipt_token into token;
 return jsonb_build_object('ok',true,'complete',completed,'receipt_token',token);
end $$;

revoke all on function public.warehouse_save_equipment_unit(bigint,bigint,text,text,text,text,text,text,text,text,boolean) from public,anon;
revoke all on function public.warehouse_save_client(bigint,text,text,text,text,boolean) from public,anon;
revoke all on function public.warehouse_deliver_request(bigint,jsonb) from public,anon;
revoke all on function public.warehouse_return_units(bigint,jsonb,text) from public,anon;
grant execute on function public.warehouse_save_equipment_unit(bigint,bigint,text,text,text,text,text,text,text,text,boolean) to authenticated;
grant execute on function public.warehouse_save_client(bigint,text,text,text,text,boolean) to authenticated;
grant execute on function public.warehouse_deliver_request(bigint,jsonb) to authenticated;
grant execute on function public.warehouse_return_units(bigint,jsonb,text) to authenticated;
